appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PVd8fjZ2VpxtPCVQ1ytHZybyerHK6IhNcVJTd9TkKKa9FMveXlg3o6KtVFy7j0FsZNeTsb+JmDQCPV5QhjGpHr+SVDom2Kc856fXHeAZy3coAl6Rhb7lZNDd1UvvFcn4jW9BwOaEfMxQRweJm0ND7HnkGn7UnxJQh7OhLhF+lKwv3aEuiYe7p6kf+3ytq2cxnyb3pWz7L1dUqCrXXCLkiaqKNEmZs3JXGJJVn5TauBnSozRxwGDfpXo2brqWjoRJ1c3CkLWmk+l3YUMX4tcFqHbNjKKs/zma3rg5lHgpUBrlyRgA7BloCsGOrWmBo12upYKZkSIIxJcIPqixbbwP/9c6CwvU1bs2Ifk6rC1cMzHR8PODChhGr/H0y8KIU5Z8YT1W4iQC0I1BPLkmnZoouog4bkEX03WeoJVhHKrqEKf6m+v07uKUv4sT5KlZk7tIQwLhXbTek14+ouJCtzKz0YFLT3kGHOJ1UQGcEhC4356C1Z3ABUcAXVAWRm1zN/CRyjTQkbZmv1UpyIx8LBUc2FPeUO53sv/9A9+DZFVUmPMdIY3sNGiKZtaLCIhDVkJQ5nog/dauiwyaKVqSmxTR3QioBBC9c2HQ9qXn2o2fbBz2NKcEvZRaYlAeEQHbN3um7338e8JX6NZ+1Uc55idAkFeYyiHIqPw7P5eRC6Z/p9w=}
conda_forge_output_validation: true
